# This is a level definition file. It is in python syntax, and should
# consist of exactly one dict.
{
    # All the colours we use.
    "colours": {
        "Blue":     (0, 0, 0.5),
        "Green":    (0, 0.5, 0),
        "Red":      (0.5, 0, 0),
        "Grey":     (0.5, 0.5, 0.5),
        "Purple":     (0.8, 0, 1),
        "White":    (1, 1, 1),
        "Yellow":   (0.8, 0.8, 0),
    },

    # The player's starting position
    "start":      (1, 25, 0),
    "start_angle": (90, -10),

    # The lights.
    "lights":   [
        {   "type":         "directional",
            "direction":    (0.3, -1.2, 0.4),
            "ambient":      (0.3, 0.3, 0.3),
            "diffuse":      (0.7, 0.7, 0.7),
            "specular":     (0.7, 0.7, 0.7),
        },
    ],

    # A list of all the floors. Floors are horizontal rectangles. Each
    # floor has a dict with these keys:
    #   pos         The coordinates of one corner
    #   edges       The vectors along the two edges, X first, then Y.
    #   colour      A tuple of (red, green, blue)
    "floors": [
        { "pos":        (24, 0, -1),
          "edges":      ((2, 0, 0), (0, 2, 0)),
          "colour":     "Purple",
        },
    ],

    # A list of the walls. Walls are parallelograms. The edges must be
    # given in anticlockwise order, looking at the side of the wall you
    # can see.
    "walls": [
        { "pos":        (6, 0, -1),
          "edges":      ((4, 0, 0), (0, 2, 0), (0, 0, -0.5)),
          "colour":     "Red",
        },
        { "pos":        (24, 2, -1),
          "edges":      ((2, 0, 0), (0, 2, 0), (0, 0, -0.5)),
          "colour":     "Green",
        },
        { "pos":        (22, 2, -1),
          "edges":      ((2, 0, 0), (0, 4, 0), (0, 0, -0.5)),
          "colour":     "Purple",
        },
        { "pos":        (14, 2, -1),
          "edges":      ((2, 0, 0), (0, 6, 0), (0, 0, -0.5)),
          "colour":     "Blue",
        },
        { "pos":        (6, 2, -1),
          "edges":      ((2, 0, 0), (0, 10, 0), (0, 0, -0.5)),
          "colour":     "Blue",
        },
        { "pos":        (12, 6, -1),
          "edges":      ((2, 0, 0), (0, 12, 0), (0, 0, -0.5)),
          "colour":     "Red",
        },
        { "pos":        (20, 4, -1),
          "edges":      ((2, 0, 0), (0, 4, 0), (0, 0, -0.5)),
          "colour":     "Yellow",
        },
        { "pos":        (18, 6, -1),
          "edges":      ((2, 0, 0), (0, 4, 0), (0, 0, -0.5)),
          "colour":     "Purple",
        },
        { "pos":        (0, 6, -1),
          "edges":      ((6, 0, 0), (0, 2, 0), (0, 0, -0.5)),
          "colour":     "Blue",
        },
        { "pos":        (0, 8, -1),
          "edges":      ((2, 0, 0), (0, 10, 0), (0, 0, -0.5)),
          "colour":     "Green",
        },
        { "pos":        (16, 8, -1),
          "edges":      ((2, 0, 0), (0, 4, 0), (0, 0, -0.5)),
          "colour":     "Red",
        },
        { "pos":        (14, 10, -1),
          "edges":      ((2, 0, 0), (0, 14, 0), (0, 0, -0.5)),
          "colour":     "Green",
        },
        { "pos":        (8, 10, -1),
          "edges":      ((2, 0, 0), (0, 10, 0), (0, 0, -0.5)),
          "colour":     "Purple",
        },
        { "pos":        (22, 10, -1),
          "edges":      ((4, 0, 0), (0, 2, 0), (0, 0, -0.5)),
          "colour":     "Blue",
        },
        { "pos":        (10, 6, -1),
          "edges":      ((2, 0, 0), (0, 4, 0), (0, 0, -0.5)),
          "colour":     "Blue",
        },
        { "pos":        (18, 0, -1),
          "edges":      ((2, 0, 0), (0, 6, 0), (0, 0, -0.5)),
          "colour":     "Blue",
        },
        { "pos":        (20, 0, -1),
          "edges":      ((2, 0, 0), (0, 2, 0), (0, 0, -0.5)),
          "colour":     "Blue",
        },
        { "pos":        (22, 12, -1),
          "edges":      ((2, 0, 0), (0, 12, 0), (0, 0, -0.5)),
          "colour":     "Blue",
        },
        { "pos":        (2, 12, -1),
          "edges":      ((2, 0, 0), (0, 14, 0), (0, 0, -0.5)),
          "colour":     "Red",
        },
        { "pos":        (16, 14, -1),
          "edges":      ((4, 0, 0), (0, 2, 0), (0, 0, -0.5)),
          "colour":     "Yellow",
        },
        { "pos":        (10, 14, -1),
          "edges":      ((2, 0, 0), (0, 4, 0), (0, 0, -0.5)),
          "colour":     "Purple",
        },
        { "pos":        (4, 14, -1),
          "edges":      ((4, 0, 0), (0, 2, 0), (0, 0, -0.5)),
          "colour":     "Blue",
        },
        { "pos":        (6, 16, -1),
          "edges":      ((2, 0, 0), (0, 6, 0), (0, 0, -0.5)),
          "colour":     "Green",
        },
        { "pos":        (18, 16, -1),
          "edges":      ((4, 0, 0), (0, 2, 0), (0, 0, -0.5)),
          "colour":     "Red",
        },
        { "pos":        (20, 18, -1),
          "edges":      ((2, 0, 0), (0, 2, 0), (0, 0, -0.5)),
          "colour":     "Green",
        },
        { "pos":        (16, 20, -1),
          "edges":      ((4, 0, 0), (0, 2, 0), (0, 0, -0.5)),
          "colour":     "Purple",
        },
        { "pos":        (18, 22, -1),
          "edges":      ((4, 0, 0), (0, 2, 0), (0, 0, -0.5)),
          "colour":     "Blue",
        },
        { "pos":        (10, 22, -1),
          "edges":      ((4, 0, 0), (0, 2, 0), (0, 0, -0.5)),
          "colour":     "Blue",
        },
        { "pos":        (0, 24, -1),
          "edges":      ((2, 0, 0), (0, 2, 0), (0, 0, -0.5)),
          "colour":     "Red",
        },
        { "pos":        (24, 22, -1),
          "edges":      ((2, 0, 0), (0, 4, 0), (0, 0, -0.5)),
          "colour":     "Yellow",
        },
        { "pos":        (4, 20, -1),
          "edges":      ((2, 0, 0), (0, 4, 0), (0, 0, -0.5)),
          "colour":     "Yellow",
        },
        { "pos":        (22, 24, -1),
          "edges":      ((2, 0, 0), (0, 2, 0), (0, 0, -0.5)),
          "colour":     "Red",
        },
        { "pos":        (0, 0, -1),
          "edges":      ((0, 0.1, 0), (26, 0, 0), (0, 0, 5)),
          "colour":     "Yellow",
        },
        { "pos":        (0, 26, -1),
          "edges":      ((0.1, 0, 0), (0, -26, 0), (0, 0, 5)),
          "colour":     "Blue",
        },
        { "pos":        (26, 0, -1),
          "edges":      ((0, 26, 0), (0.1, 0, 0), (0, 0, 5)),
          "colour":     "Red",
        },
        { "pos":        (26, 26, -1),
          "edges":      ((-26, 0, 0), (0, 0.1, 0), (0, 0, 5)),
          "colour":     "Purple",
        },
        { "pos":        (8, 2, -1),
          "edges":      ((0, 0.1, 0), (2, 0, 0), (0, 0, 5)),
          "colour":     "Purple",
        },
        { "pos":        (0.1, 24, -1),
          "edges":      ((0, 0.1, 0), (1.9, 0, 0), (0, 0, 5)),
          "colour":     "Purple",
        },
        { "pos":        (2, 18, -1),
          "edges":      ((0, 6.1, 0), (0.1, 0, 0), (0, 0, 5)),
          "colour":     "Yellow",
        },
        { "pos":        (0, 18, -1),
          "edges":      ((0, 0.1, 0), (2, 0, 0), (0, 0, 5)),
          "colour":     "Blue",
        },
        { "pos":        (4, 24, -1),
          "edges":      ((0, 0.1, 0), (2, 0, 0), (0, 0, 5)),
          "colour":     "Red",
        },
        { "pos":        (4, 24.1, -1),
          "edges":      ((0, 1.9, 0), (0.1, 0, 0), (0, 0, 5)),
          "colour":     "Blue",
        },
        { "pos":        (4, 16, -1),
          "edges":      ((0, 6, 0), (0.1, 0, 0), (0, 0, 5)),
          "colour":     "Green",
        },
        { "pos":        (2, 16, -1),
          "edges":      ((0, 0.1, 0), (2, 0, 0), (0, 0, 5)),
          "colour":     "White",
        },
        { "pos":        (6, 22, -1),
          "edges":      ((0, 2.1, 0), (0.1, 0, 0), (0, 0, 5)),
          "colour":     "Grey",
        },
        { "pos":        (6.1, 22, -1),
          "edges":      ((0, 0.1, 0), (1.9, 0, 0), (0, 0, 5)),
          "colour":     "Green",
        },
        { "pos":        (8.1, 20, -1),
          "edges":      ((0, 0.1, 0), (1.9, 0, 0), (0, 0, 5)),
          "colour":     "White",
        },
        { "pos":        (8, 20, -1),
          "edges":      ((0, 2.1, 0), (0.1, 0, 0), (0, 0, 5)),
          "colour":     "Grey",
        },
        { "pos":        (10.1, 18, -1),
          "edges":      ((0, 0.1, 0), (3.9, 0, 0), (0, 0, 5)),
          "colour":     "White",
        },
        { "pos":        (10, 18, -1),
          "edges":      ((0, 2.1, 0), (0.1, 0, 0), (0, 0, 5)),
          "colour":     "Green",
        },
        { "pos":        (10, 22, -1),
          "edges":      ((0, 0.1, 0), (4, 0, 0), (0, 0, 5)),
          "colour":     "Grey",
        },
        { "pos":        (10, 24, -1),
          "edges":      ((0, 0.1, 0), (6, 0, 0), (0, 0, 5)),
          "colour":     "Green",
        },
        { "pos":        (20.1, 20, -1),
          "edges":      ((0, 0.1, 0), (1.9, 0, 0), (0, 0, 5)),
          "colour":     "Red",
        },
        { "pos":        (20, 20, -1),
          "edges":      ((0, 2, 0), (0.1, 0, 0), (0, 0, 5)),
          "colour":     "Green",
        },
        { "pos":        (22, 22, -1),
          "edges":      ((-2, 0, 0), (0, 0.1, 0), (0, 0, 5)),
          "colour":     "Blue",
        },
        { "pos":        (22, 22.1, -1),
          "edges":      ((0.1, 0, 0), (0, -2.1, 0), (0, 0, 5)),
          "colour":     "Grey",
        },
        { "pos":        (4.1, 20, -1),
          "edges":      ((0, 0.1, 0), (1.9, 0, 0), (0, 0, 5)),
          "colour":     "Yellow",
        },
        { "pos":        (6.1, 18, -1),
          "edges":      ((0, 0.1, 0), (1.9, 0, 0), (0, 0, 5)),
          "colour":     "Purple",
        },
        { "pos":        (6, 16, -1),
          "edges":      ((0, 4.1, 0), (0.1, 0, 0), (0, 0, 5)),
          "colour":     "White",
        },
        { "pos":        (2, 12, -1),
          "edges":      ((0, 4, 0), (0.1, 0, 0), (0, 0, 5)),
          "colour":     "Red",
        },
        { "pos":        (4, 12, -1),
          "edges":      ((-1.9, 0, 0),(0, 0.1, 0), (0, 0, 5)),
          "colour":     "Green",
        },
        { "pos":        (4, 12, -1),
          "edges":      ((0, 2, 0), (0.1, 0, 0), (0, 0, 5)),
          "colour":     "Blue",
        },
        { "pos":        (4, 14, -1),
          "edges":      ((0, 0.1, 0),(4, 0, 0), (0, 0, 5)),
          "colour":     "Grey",
        },
        { "pos":        (8, 12, -1),
          "edges":      ((0, 4, 0), (0.1, 0, 0), (0, 0, 5)),
          "colour":     "Yellow",
        },
        { "pos":        (10.1, 14, -1),
          "edges":      ((0, 0.1, 0), (1.9, 0, 0), (0, 0, 5)),
          "colour":     "Purple",
        },
        { "pos":        (10, 10, -1),
          "edges":      ((0, 6, 0), (0.1, 0, 0), (0, 0, 5)),
          "colour":     "White",
        },
        { "pos":        (0, 6, -1),
          "edges":      ((0, 0.1, 0), (6, 0, 0), (0, 0, 5)),
          "colour":     "Red",
        },
        { "pos":        (6, 0.1, -1),
          "edges":      ((0, 5.9, 0), (0.1, 0, 0), (0, 0, 5)),
          "colour":     "Green",
        },
        { "pos":        (4, 8, -1),
          "edges":      ((0, 0.1, 0), (2, 0, 0), (0, 0, 5)),
          "colour":     "Blue",
        },
        { "pos":        (6, 8, -1),
          "edges":      ((0, 4, 0),(0.1, 0, 0), (0, 0, 5)),
          "colour":     "Grey",
        },
        { "pos":        (6, 12, -1),
          "edges":      ((0, 0.1, 0), (2, 0, 0), (0, 0, 5)),
          "colour":     "Yellow",
        },
        { "pos":        (8, 2, -1),
          "edges":      ((0, 8, 0), (0.1, 0, 0), (0, 0, 5)),
          "colour":     "Purple",
        },
        { "pos":        (8, 10, -1),
          "edges":      ((0, 0.1, 0), (2, 0, 0), (0, 0, 5)),
          "colour":     "White",
        },
        { "pos":        (14, 18, -1),
          "edges":      ((0, 4, 0), (0.1, 0, 0), (0, 0, 5)),
          "colour":     "Red",
        },
        { "pos":        (16, 22.1, -1),
          "edges":      ((0, 2, 0), (0.1, 0, 0), (0, 0, 5)),
          "colour":     "Green",
        },
        { "pos":        (16, 22, -1),
          "edges":      ((0, 0.1, 0), (2, 0, 0), (0, 0, 5)),
          "colour":     "Blue",
        },
        { "pos":        (18, 22, -1),
          "edges":      ((0, 2.1, 0),(0.1, 0, 0), (0, 0, 5)),
          "colour":     "Grey",
        },
        { "pos":        (18.1, 24, -1),
          "edges":      ((0, 0.1, 0), (5.9, 0, 0), (0, 0, 5)),
          "colour":     "Yellow",
        },
        { "pos":        (24, 22, -1),
          "edges":      ((0, 0.1, 0), (2, 0, 0), (0, 0, 5)),
          "colour":     "Purple",
        },
        { "pos":        (24, 12, -1),
          "edges":      ((0, 10, 0), (0.1, 0, 0), (0, 0, 5)),
          "colour":     "White",
        },
        { "pos":        (24.1, 12, -1),
          "edges":      ((0, 0.1, 0), (1.9, 0, 0), (0, 0, 5)),
          "colour":     "Red",
        },
        { "pos":        (22, 10, -1),
          "edges":      ((0, 0.1, 0), (4, 0, 0), (0, 0, 5)),
          "colour":     "Green",
        },
        { "pos":        (22, 10, -1),
          "edges":      ((0, 8, 0), (0.1, 0, 0), (0, 0, 5)),
          "colour":     "Blue",
        },
        { "pos":        (16, 16.1, -1),
          "edges":      ((0, 3.9, 0),(0.1, 0, 0), (0, 0, 5)),
          "colour":     "Yellow",
        },
        { "pos":        (16, 16, -1),
          "edges":      ((0, 0.1, 0), (2, 0, 0), (0, 0, 5)),
          "colour":     "Grey",
        },
        { "pos":        (20, 20, -1),
          "edges":      ((-4, 0, 0), (0, 0.1, 0), (0, 0, 5)),
          "colour":     "Purple", 
        },
        { "pos":        (20, 20, -1),
          "edges":      ((0.1, 0, 0), (0, -2, 0),  (0, 0, 5)),
          "colour":     "White",
        },
        { "pos":        (18, 16, -1),
          "edges":      ((0, 2, 0), (0.1, 0, 0), (0, 0, 5)),
          "colour":     "Red",
        },
        { "pos":        (18, 18, -1),
          "edges":      ((0, 0.1, 0), (2, 0, 0), (0, 0, 5)),
          "colour":     "Green",
        },
        { "pos":        (20, 16.1, -1),
          "edges":      ((0, 0.1, 0), (1.9, 0, 0), (0, 0, 5)),
          "colour":     "Blue",
        },
        { "pos":        (20, 14, -1),
          "edges":      ((0, 2.1, 0),(0.1, 0, 0), (0, 0, 5)),
          "colour":     "Yellow",
        },
        { "pos":        (16, 14, -1),
          "edges":      ((0, 0.1, 0), (4, 0, 0), (0, 0, 5)),
          "colour":     "Grey",
        },
        { "pos":        (16, 14, -1),
          "edges":      ((0.1, 0, 0), (0, -2, 0),(0, 0, 5)),
          "colour":     "Purple", 
        },
        { "pos":        (12, 16, -1),
          "edges":      ((0, 0.1, 0), (4, 0, 0),  (0, 0, 5)),
          "colour":     "White",
        },
    ],

    "items": [
        {   "type":     "Portal",
            "pos":      (25, 1, 0),
            "to":       None,
        },
    ],

    # We die if we fall this low.
    "doom_z":   -20,
}
